### ISSUE TITLE
并发转换报错

### ISSUE THREAD

**Issue by ferdinandhuang** [Trisia/ofdrw#102]
在并发转换OFD到PDF的时候（无论是通过Path或Stream）只有少数返回成功（1-2条），其余的均后台报错：
`
java.io.IOException: The TrueType font null does not contain a 'cmap' table
	at org.apache.fontbox.ttf.TrueTypeFont.getUnicodeCmapImpl(TrueTypeFont.java:553) ~[fontbox-2.0.21.jar:2.0.21]
	at org.apache.fontbox.ttf.TrueTypeFont.getUnicodeCmapLookup(TrueTypeFont.java:533) ~[fontbox-2.0.21.jar:2.0.21]
	at org.apache.fontbox.ttf.TrueTypeFont.getUnicodeCmapLookup(TrueTypeFont.java:519) ~[fontbox-2.0.21.jar:2.0.21]
	at org.apache.fontbox.ttf.TTFSubsetter.<init>(TTFSubsetter.java:90) ~[fontbox-2.0.21.jar:2.0.21]
	at org.apache.pdfbox.pdmodel.font.TrueTypeEmbedder.subset(TrueTypeEmbedder.java:346) ~[pdfbox-2.0.21.jar:2.0.21]
	at org.apache.pdfbox.pdmodel.font.PDType0Font.subset(PDType0Font.java:256) ~[pdfbox-2.0.21.jar:2.0.21]
	at org.apache.pdfbox.pdmodel.PDDocument.save(PDDocument.java:1349) ~[pdfbox-2.0.21.jar:2.0.21]
	at org.ofdrw.converter.ConvertHelper.ofd2pdf(ConvertHelper.java:62) [ofdrw-converter-1.7.2.jar:na]
	at org.ofdrw.converter.ConvertHelper.toPdf(ConvertHelper.java:101) [ofdrw-converter-1.7.2.jar:na]
`

**Comment by tryob** [comment]
可以把测试代码贴出来，我测试下看看

**Comment by Trisia** [comment]
无法重现，关闭
