### ISSUE TITLE
调用canvas的drawImage时，如果资源文件重复会抛出文件已存在异常

### ISSUE THREAD

**Issue by minghu-zhang** [Trisia/ofdrw#50]
```
 canvas.setDrawer(ctx -> {
                FontSetting fontSetting = new FontSetting(5, FontSet.get(FontName.NotoSerif))
                        .setCharDirection(0)
                        .setReadDirection(0);
                ctx.setFillColor(255, 0, 0);
                ctx.setFont(fontSetting);
                ctx.fillText("你好 Hello World!", 60, 60);
                ctx.drawImage(Paths.get("src/test/resources/eg_tulip.jpg"), 0, 0, 50, 50);
            });
```
该文件 【eg_tulip.jpg】在空间里已存在，报错代码：
```
public VirtualContainer putFile(Path file) throws IOException {
        if (file == null || Files.notExists(file) || Files.isDirectory(file)) {
            // 为空或是一个文件夹，或者不存在
            return this;
        }
        String fileName = file.getFileName().toString();
        Path target = Paths.get(fullPath, fileName);
        // 如果文件已经在目录中那么不做任何事情
        if (target.toAbsolutePath().toString()
                .equals(file.toAbsolutePath().toString())) {
            return this;
        }
        // 复制文件到指定目录（该处报错）
        Files.copy(file, target);

        return this;
    }
```
错误如下：
```
java.nio.file.FileAlreadyExistsException: C:\Users\gmgmagw\AppData\Local\Temp\ofd-tmp-2955131297989901349\Doc_0\Res\eg_tulip.jpg
	at sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:124)
	at sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:278)
	at java.nio.file.Files.copy(Files.java:1274)
	at org.ofdrw.pkg.container.VirtualContainer.putFile(VirtualContainer.java:151)
	at org.ofdrw.pkg.container.ResDir.add(ResDir.java:36)
	at org.ofdrw.pkg.container.DocDir.addResource(DocDir.java:243)
	at org.ofdrw.layout.ResManager.addImage(ResManager.java:208)
	at org.ofdrw.layout.element.canvas.DrawContext.drawImage(DrawContext.java:590)
	at org.ofdrw.layout.element.canvas.DrawContextTest.lambda$addText$20(DrawContextTest.java:559)
	at org.ofdrw.layout.engine.render.CanvasRender.render(CanvasRender.java:48)
	at org.ofdrw.layout.engine.VPageParseEngine.convert2Layer(VPageParseEngine.java:184)
```

**Comment by Trisia** [comment]
这是因为文档中已经有一个同名的文件，关于这种情况下的处理不知道你有什么建议。

**Comment by Trisia** [comment]
[48d723c](https://github.com/Trisia/ofdrw/commit/48d723ca8eec731c05624ff37687c1c355a762c3)
